CC=arm-none-eabi-
CFLAGS=-mcpu=cortex-m3 -mthumb -gdwarf-2
INCS=-I .
LIBS=
SRC=$(wildcard *.c)
OBJ=$(SRC:.c=.o)
As=$(wildcard *.s)
AsOBJ=$(As:.s=.o)
project_name=HPSD
all: $(project_name).bin
	@echo "Done ya Basha"
$(project_name).bin: $(project_name).elf
	$(CC)objcopy.exe -O binary $<  $@
$(project_name).elf: $(OBJ) $(AsOBJ)
	$(CC)ld.exe -T linker_script.ld $(LIBS) $(OBJ) $(AsOBJ) -o $@ -Map=mapfile.map
%.o: %.c
	$(CC)gcc.exe $(CFLAGS) $(INCS) -c $< -o $@
%.o: %.s
	$(CC)as.exe $(CFLAGS) $< -o $@
clean:
	rm *.elf *.bin
clean_all:
	rm *.o *.elf *.bin
	@echo "clean done"